# Generated by Django 4.2 on 2024-05-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_ver_code_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ver_code",
            field=models.CharField(default="732221", max_length=6, verbose_name="Код"),
        ),
    ]
