# Generated by Django 4.2 on 2024-05-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_ver_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("cancel_user_is_active", "Can cancel user is_active"),
                ),
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="ver_code",
            field=models.CharField(default="837587", max_length=6, verbose_name="Код"),
        ),
    ]
