# Generated by Django 4.2 on 2024-05-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_options_alter_user_ver_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ver_code",
            field=models.CharField(default="945481", max_length=6, verbose_name="Код"),
        ),
    ]
