# Generated by Django 4.2 on 2024-05-23 16:47

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_mailing_next_send_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="create_date",
        ),
        migrations.AddField(
            model_name="mailing",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                verbose_name="Дата и время создания рассылки рассылки",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="quit_at",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                verbose_name="Дата и время окончания работы рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="next_send_time",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                verbose_name="Дата и время отправки рассылки",
            ),
        ),
    ]
