# Generated by Django 4.2 on 2024-05-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_remove_mailing_create_date_mailing_create_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ("id",),
                "permissions": (
                    (
                        "cancel_mailing_status_mailing",
                        "Can cancel mailing status_mailing",
                    ),
                ),
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
