# Generated by Django 4.2 on 2024-05-26 15:08

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 26, 15, 7, 59, 466722, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время создания рассылки рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="next_send_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 26, 15, 7, 59, 466722, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время отправки рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="quit_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 26, 15, 7, 59, 466722, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время окончания работы рассылки",
            ),
        ),
    ]
