# Generated by Django 4.2 on 2024-05-26 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing",
            "0009_alter_mailing_create_at_alter_mailing_next_send_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="create_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата и время создания рассылки рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="next_send_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата и время отправки рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="quit_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата и время окончания работы рассылки",
            ),
        ),
    ]
