# Generated by Django 4.2 on 2024-05-23 07:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="BlogView",
        ),
    ]
