# Generated by Django 4.2 on 2024-05-23 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_rename_blog_blogview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogview",
            name="img",
        ),
        migrations.AddField(
            model_name="blogview",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="blogview",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="blogs/", verbose_name="Фотография"
            ),
        ),
        migrations.AddField(
            model_name="blogview",
            name="slug",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="blogview",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="blogview",
            name="content",
            field=models.TextField(verbose_name="содержимое"),
        ),
        migrations.AlterField(
            model_name="blogview",
            name="created_at",
            field=models.DateField(verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="blogview",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="количество просмотров"),
        ),
    ]
